host: localhost:3000
basePath: /api/v0
schemes:
    - http
securityDefinitions:
    ApiKey:
        type: apiKey
        in: header
        name: Authorization
consumes:
    - application/json
produces:
    - application/json
info:
    contact:
        name: Ryan's mom
    description: Backend API for Brood Clash
    title: Brood Clash
    version: 0.1.0
definitions:
    answer:
        type: object
        required:
            - text
            - points
            - revealed
        properties:
            id:
                type: integer
                format: int64
                readOnly: true
            text:
                type: string
                minLength: 1
            points:
                type: integer
                format: int32
            revealed:
                type: boolean
    question:
        type: object
        required:
            - text
        properties:
            id:
                type: integer
                format: int64
                readOnly: true
            text:
                type: string
                minLength: 1
            answers:
                type: array
                items:
                    $ref: "#/definitions/answer"
                minItems: 8
                maxItems: 8
paths:
    # API
    /authTest:
        get:
            summary: Test the authorization code
            operationId: authTest
            security:
                - ApiKey: []
            responses:
                204:
                    description: No Content
                401:
                    description: Unauthorized
                default:
                    description: Unknown error
    /questions:
        get:
            summary: Get all questions
            operationId: getQuestions
            security:
                - ApiKey: []
            responses:
                200:
                    description: OK
                    schema:
                        type: array
                        items:
                            $ref: "#/definitions/question"
                401:
                    description: Unauthorized
                default:
                    description: Unknown error
        post:
            summary: Create a new question
            operationId: createQuestions
            security:
                - ApiKey: []
            parameters:
                - name: questions
                  in: body
                  schema:
                    type: array
                    items:
                      $ref: "#/definitions/question"
                  required: true
            responses:
                201:
                    description: Created
                400:
                    description: Bad Request
                401:
                    description: Unauthorized
                default:
                    description: Unknown error
    /questions/{id}:
        get:
            summary: Get a question by ID
            operationId: getQuestion
            security:
                - ApiKey: []
            parameters:
                - name: id
                  in: path
                  type: integer
                  format: int64
                  required: true
            responses:
                200:
                    description: OK
                    schema:
                        $ref: "#/definitions/question"
                401:
                    description: Unauthorized
                404:
                    description: Not Found
                default:
                    description: Unknown error
    /questions/{questionId}/answers/{answerId}/reveal:
        post:
            summary: Marks an answer as revealed
            operationId: revealAnswer
            security:
                - ApiKey: []
            parameters:
                - name: questionId
                  in: path
                  type: integer
                  format: int64
                  required: true
                - name: answerId
                  in: path
                  type: integer
                  format: int64
                  required: true
            responses:
                204:
                    description: OK
                401:
                    description: Unauthorized
                404:
                    description: Not Found
                default:
                    description: Unknown error

    # PRESENTER
    /presenter/websocket:
        get:
            summary: Establish a presenter websocket
            operationId: websocket
            schemes: ws
            responses:
                101:
                    description: Switching Protocols

swagger: "2.0"

# e := echo.New()
#	e.Use(middleware.LoggerWithConfig(middleware.LoggerConfig{
#		Format: "method=${method}, uri=${uri}, status=${status}\n",
#	}))
# e.Use(middleware.CORS())
# e.GET("/present", api.Present)

# g := e.Group("/api")
# g.Use(middleware.KeyAuthWithConfig(middleware.KeyAuthConfig{
# 	KeyLookup: "header:Authorization",
# 	Validator: services.LoginCodeValidator,
# }))
# g.GET("/code/valid", api.ValidateCode)

# q := g.Group("/questions")
# q.Use(ffmiddleware.DetectQuestionUpdates)
# q.GET("", api.GetQuestions)
# q.POST("", api.AddQuestions)
# q.GET("/:id", api.GetQuestion)
# q.PUT("/:questionId/answers/:answerId/reveal", api.RevealAnswer)

# e.HideBanner = true
#_ = e.Start(":1323")
