host: localhost:3000
basePath: /api/v0
schemes:
    - http
securityDefinitions:
    ApiKeyAuth:
        type: apiKey
        in: header
        name: Authorization
consumes:
- application/json
info:
    contact:
        name: Ryan's mom
    description: Backend API for Brood Clash
    title: Brood Clash
    version: 0.1.0
definitions:
    answer:
        type: object
        required:
            - text
            - points
        properties:
            id:
                type: integer
                format: int64
                readOnly: true
            text:
                type: string
                minLength: 1
            points:
                type: integer
                format: int32
            revealed:
                type: boolean
    question:
        type: object
        required:
            - text
        properties:
            id:
                type: integer
                format: int64
                readOnly: true
            text:
                type: string
                minLength: 1
            answers:
                type: array
                items:
                    $ref: "#/definitions/answer"
                minItems: 8
                maxItems: 8
paths:
    # CONTROLLER
    /controller/authTest:
        get:
            summary: Test the authorization code
            operationId: authTest
            security:
                - ApiKeyAuth: []
            tags:
                - controller
            responses:
                200:
                    description: OK
                401:
                    description: Unauthorized
    # PRESENTER


produces:
- application/json
schemes:
- http
swagger: "2.0"

# e := echo.New()
#	e.Use(middleware.LoggerWithConfig(middleware.LoggerConfig{
#		Format: "method=${method}, uri=${uri}, status=${status}\n",
#	}))
# e.Use(middleware.CORS())
# e.GET("/present", api.Present)

# g := e.Group("/api")
# g.Use(middleware.KeyAuthWithConfig(middleware.KeyAuthConfig{
# 	KeyLookup: "header:Authorization",
# 	Validator: services.LoginCodeValidator,
# }))
# g.GET("/code/valid", api.ValidateCode)

# q := g.Group("/questions")
# q.Use(ffmiddleware.DetectQuestionUpdates)
# q.GET("", api.GetQuestions)
# q.POST("", api.AddQuestions)
# q.GET("/:id", api.GetQuestion)
# q.PUT("/:questionId/answers/:answerId/reveal", api.RevealAnswer)

# e.HideBanner = true
#_ = e.Start(":1323")
