/*
 * Brood-Clash API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.13
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BroodClashApi);
  }
}(this, function(expect, BroodClashApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('ModelsQuestion', function() {
      beforeEach(function() {
        instance = new BroodClashApi.ModelsQuestion();
      });

      it('should create an instance of ModelsQuestion', function() {
        // TODO: update the code to test ModelsQuestion
        expect(instance).to.be.a(BroodClashApi.ModelsQuestion);
      });

      it('should have the property answers (base name: "answers")', function() {
        // TODO: update the code to test the property answers
        expect(instance).to.have.property('answers');
        // expect(instance.answers).to.be(expectedValueLiteral);
      });

      it('should have the property hasBeenShown (base name: "hasBeenShown")', function() {
        // TODO: update the code to test the property hasBeenShown
        expect(instance).to.have.property('hasBeenShown');
        // expect(instance.hasBeenShown).to.be(expectedValueLiteral);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property text (base name: "text")', function() {
        // TODO: update the code to test the property text
        expect(instance).to.have.property('text');
        // expect(instance.text).to.be(expectedValueLiteral);
      });

    });
  });

}));
