// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Brood Clash
Backend API for Brood Clash


    Schemes:
      http
    Host: localhost:3000
    BasePath: /api/v0
    Version: 0.1.0
    Contact: Ryan's mom

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
