basePath: /api/v1
definitions:
  models.Answer:
    properties:
      id:
        readOnly: true
        type: string
      points:
        maximum: 100
        minimum: 1
        type: integer
      revealed:
        readOnly: true
        type: boolean
      text:
        type: string
    type: object
  models.Question:
    properties:
      answers:
        items:
          $ref: '#/definitions/models.Answer'
        type: array
      hasBeenShown:
        readOnly: true
        type: boolean
      id:
        readOnly: true
        type: string
      text:
        type: string
    type: object
info:
  contact: {}
  license: {}
  title: Brood-Clash API
  version: "1.0"
paths:
  /answers/{id}/reveal:
    post:
      operationId: reveal-answer
      parameters:
      - description: Answer ID, must be UUID
        format: uuid
        in: path
        name: id
        required: true
        type: string
      responses:
        "204":
          description: Success
        "400":
          description: Couldn't parse ID param into UUID
        "401":
          description: Unauthorised
        "404":
          description: Answer doesn't exist
        "418":
          description: Answer already revealed
          schema:
            type: string
      security:
      - CodeAuth: []
      summary: Reveal answer
  /currentQuestion:
    get:
      operationId: get-current-question
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/models.Question'
        "401":
          description: Unauthorised
        "404":
          description: No current question
      security:
      - CodeAuth: []
      summary: Get Current Question
  /incorrectAnswer:
    post:
      operationId: incorrect-answer
      responses:
        "204":
          description: Success
        "401":
          description: Unauthorised
      security:
      - CodeAuth: []
      summary: Incorrect Answer
  /questions:
    get:
      operationId: get-all-questions
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            items:
              $ref: '#/definitions/models.Question'
            type: array
        "401":
          description: Unauthorised
        "500":
          description: Failed to retrieve questions
      security:
      - CodeAuth: []
      summary: Get All Questions
    post:
      consumes:
      - application/json
      operationId: post-questions
      parameters:
      - description: Questions to be created
        in: body
        name: questions
        required: true
        schema:
          items:
            $ref: '#/definitions/models.Question'
          type: array
      responses:
        "201":
          description: Questions created
        "202":
          description: Some questions couldn't be created
        "401":
          description: Unauthorised
      security:
      - CodeAuth: []
      summary: Post Questions
  /questions/{id}:
    delete:
      operationId: delete-question
      parameters:
      - description: Question ID, must be UUID
        format: uuid
        in: path
        name: id
        required: true
        type: string
      responses:
        "204":
          description: Success
        "400":
          description: Couldn't parse ID param into UUID
        "401":
          description: Unauthorised
        "404":
          description: Question doesn't exist
        "500":
          description: Unknown error
      security:
      - CodeAuth: []
      summary: Delete Question
  /questions/{id}/select:
    post:
      operationId: select-question
      parameters:
      - description: Question ID, must be UUID
        format: uuid
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/models.Question'
        "401":
          description: Unauthorised
        "404":
          description: Question not found
        "418":
          description: Question has already been shown before
        "500":
          description: Unknown error
      security:
      - CodeAuth: []
      summary: Select Question
  /reset:
    post:
      operationId: reset-game-state
      responses:
        "204":
          description: Successfully reset the game state
        "401":
          description: Unauthorised
        "500":
          description: Failed to reset game state
      security:
      - CodeAuth: []
      summary: Reset Game State
  /test:
    get:
      operationId: test
      responses:
        "204":
          description: Success
        "401":
          description: Unauthorised
      security:
      - CodeAuth: []
      summary: Test
securityDefinitions:
  CodeAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
