basePath: /api/v1
host: localhost:8080
info:
  contact: {}
  license: {}
  title: Brood-Clash API
  version: "1.0"
paths:
  /answers/{id}/reveal:
    post:
      consumes:
      - application/json
      operationId: reveal-answer
      parameters:
      - description: Answer ID, must be UUID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: Success
        "400":
          description: Couldn't parse ID param into UUID
        "403":
          description: Unauthorised
        "404":
          description: Answer doesn't exist
        "418":
          description: Answer already revealed
          schema:
            type: string
      security:
      - CodeAuth: []
      summary: Reveal answer
securityDefinitions:
  CodeAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
