// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// CreateQuestionsCreatedCode is the HTTP code returned for type CreateQuestionsCreated
const CreateQuestionsCreatedCode int = 201

/*CreateQuestionsCreated Created

swagger:response createQuestionsCreated
*/
type CreateQuestionsCreated struct {
}

// NewCreateQuestionsCreated creates CreateQuestionsCreated with default headers values
func NewCreateQuestionsCreated() *CreateQuestionsCreated {

	return &CreateQuestionsCreated{}
}

// WriteResponse to the client
func (o *CreateQuestionsCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// CreateQuestionsBadRequestCode is the HTTP code returned for type CreateQuestionsBadRequest
const CreateQuestionsBadRequestCode int = 400

/*CreateQuestionsBadRequest Bad Request

swagger:response createQuestionsBadRequest
*/
type CreateQuestionsBadRequest struct {
}

// NewCreateQuestionsBadRequest creates CreateQuestionsBadRequest with default headers values
func NewCreateQuestionsBadRequest() *CreateQuestionsBadRequest {

	return &CreateQuestionsBadRequest{}
}

// WriteResponse to the client
func (o *CreateQuestionsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// CreateQuestionsUnauthorizedCode is the HTTP code returned for type CreateQuestionsUnauthorized
const CreateQuestionsUnauthorizedCode int = 401

/*CreateQuestionsUnauthorized Unauthorized

swagger:response createQuestionsUnauthorized
*/
type CreateQuestionsUnauthorized struct {
}

// NewCreateQuestionsUnauthorized creates CreateQuestionsUnauthorized with default headers values
func NewCreateQuestionsUnauthorized() *CreateQuestionsUnauthorized {

	return &CreateQuestionsUnauthorized{}
}

// WriteResponse to the client
func (o *CreateQuestionsUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

/*CreateQuestionsDefault Unknown error

swagger:response createQuestionsDefault
*/
type CreateQuestionsDefault struct {
	_statusCode int
}

// NewCreateQuestionsDefault creates CreateQuestionsDefault with default headers values
func NewCreateQuestionsDefault(code int) *CreateQuestionsDefault {
	if code <= 0 {
		code = 500
	}

	return &CreateQuestionsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the create questions default response
func (o *CreateQuestionsDefault) WithStatusCode(code int) *CreateQuestionsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the create questions default response
func (o *CreateQuestionsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WriteResponse to the client
func (o *CreateQuestionsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(o._statusCode)
}
