// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// CreateQuestionsHandlerFunc turns a function with the right signature into a create questions handler
type CreateQuestionsHandlerFunc func(CreateQuestionsParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateQuestionsHandlerFunc) Handle(params CreateQuestionsParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// CreateQuestionsHandler interface for that can handle valid create questions params
type CreateQuestionsHandler interface {
	Handle(CreateQuestionsParams, interface{}) middleware.Responder
}

// NewCreateQuestions creates a new http.Handler for the create questions operation
func NewCreateQuestions(ctx *middleware.Context, handler CreateQuestionsHandler) *CreateQuestions {
	return &CreateQuestions{Context: ctx, Handler: handler}
}

/*CreateQuestions swagger:route POST /questions createQuestions

Create a new question

*/
type CreateQuestions struct {
	Context *middleware.Context
	Handler CreateQuestionsHandler
}

func (o *CreateQuestions) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCreateQuestionsParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
