// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// RevealAnswerNoContentCode is the HTTP code returned for type RevealAnswerNoContent
const RevealAnswerNoContentCode int = 204

/*RevealAnswerNoContent OK

swagger:response revealAnswerNoContent
*/
type RevealAnswerNoContent struct {
}

// NewRevealAnswerNoContent creates RevealAnswerNoContent with default headers values
func NewRevealAnswerNoContent() *RevealAnswerNoContent {

	return &RevealAnswerNoContent{}
}

// WriteResponse to the client
func (o *RevealAnswerNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// RevealAnswerUnauthorizedCode is the HTTP code returned for type RevealAnswerUnauthorized
const RevealAnswerUnauthorizedCode int = 401

/*RevealAnswerUnauthorized Unauthorized

swagger:response revealAnswerUnauthorized
*/
type RevealAnswerUnauthorized struct {
}

// NewRevealAnswerUnauthorized creates RevealAnswerUnauthorized with default headers values
func NewRevealAnswerUnauthorized() *RevealAnswerUnauthorized {

	return &RevealAnswerUnauthorized{}
}

// WriteResponse to the client
func (o *RevealAnswerUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// RevealAnswerNotFoundCode is the HTTP code returned for type RevealAnswerNotFound
const RevealAnswerNotFoundCode int = 404

/*RevealAnswerNotFound Not Found

swagger:response revealAnswerNotFound
*/
type RevealAnswerNotFound struct {
}

// NewRevealAnswerNotFound creates RevealAnswerNotFound with default headers values
func NewRevealAnswerNotFound() *RevealAnswerNotFound {

	return &RevealAnswerNotFound{}
}

// WriteResponse to the client
func (o *RevealAnswerNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

/*RevealAnswerDefault Unknown error

swagger:response revealAnswerDefault
*/
type RevealAnswerDefault struct {
	_statusCode int
}

// NewRevealAnswerDefault creates RevealAnswerDefault with default headers values
func NewRevealAnswerDefault(code int) *RevealAnswerDefault {
	if code <= 0 {
		code = 500
	}

	return &RevealAnswerDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the reveal answer default response
func (o *RevealAnswerDefault) WithStatusCode(code int) *RevealAnswerDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the reveal answer default response
func (o *RevealAnswerDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WriteResponse to the client
func (o *RevealAnswerDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(o._statusCode)
}
