// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// RevealAnswerHandlerFunc turns a function with the right signature into a reveal answer handler
type RevealAnswerHandlerFunc func(RevealAnswerParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn RevealAnswerHandlerFunc) Handle(params RevealAnswerParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// RevealAnswerHandler interface for that can handle valid reveal answer params
type RevealAnswerHandler interface {
	Handle(RevealAnswerParams, interface{}) middleware.Responder
}

// NewRevealAnswer creates a new http.Handler for the reveal answer operation
func NewRevealAnswer(ctx *middleware.Context, handler RevealAnswerHandler) *RevealAnswer {
	return &RevealAnswer{Context: ctx, Handler: handler}
}

/*RevealAnswer swagger:route POST /questions/{questionId}/answers/{answerId}/reveal revealAnswer

Marks an answer as revealed

*/
type RevealAnswer struct {
	Context *middleware.Context
	Handler RevealAnswerHandler
}

func (o *RevealAnswer) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewRevealAnswerParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
