// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// WebsocketHandlerFunc turns a function with the right signature into a websocket handler
type WebsocketHandlerFunc func(WebsocketParams) middleware.Responder

// Handle executing the request and returning a response
func (fn WebsocketHandlerFunc) Handle(params WebsocketParams) middleware.Responder {
	return fn(params)
}

// WebsocketHandler interface for that can handle valid websocket params
type WebsocketHandler interface {
	Handle(WebsocketParams) middleware.Responder
}

// NewWebsocket creates a new http.Handler for the websocket operation
func NewWebsocket(ctx *middleware.Context, handler WebsocketHandler) *Websocket {
	return &Websocket{Context: ctx, Handler: handler}
}

/*Websocket swagger:route GET /presenter/websocket websocket

Establish a presenter websocket

*/
type Websocket struct {
	Context *middleware.Context
	Handler WebsocketHandler
}

func (o *Websocket) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewWebsocketParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
