// Code generated by go-swagger; DO NOT EDIT.

package presenter

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// WebsocketOKCode is the HTTP code returned for type WebsocketOK
const WebsocketOKCode int = 200

/*WebsocketOK OK

swagger:response websocketOK
*/
type WebsocketOK struct {
}

// NewWebsocketOK creates WebsocketOK with default headers values
func NewWebsocketOK() *WebsocketOK {

	return &WebsocketOK{}
}

// WriteResponse to the client
func (o *WebsocketOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
