// Code generated by go-swagger; DO NOT EDIT.

package presenter

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// WebsocketSwitchingProtocolsCode is the HTTP code returned for type WebsocketSwitchingProtocols
const WebsocketSwitchingProtocolsCode int = 101

/*WebsocketSwitchingProtocols Switching Protocols

swagger:response websocketSwitchingProtocols
*/
type WebsocketSwitchingProtocols struct {
}

// NewWebsocketSwitchingProtocols creates WebsocketSwitchingProtocols with default headers values
func NewWebsocketSwitchingProtocols() *WebsocketSwitchingProtocols {

	return &WebsocketSwitchingProtocols{}
}

// WriteResponse to the client
func (o *WebsocketSwitchingProtocols) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(101)
}
