/*
 * Brood Clash
 * Backend API for Brood Clash
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient';

/**
 * The Answer model module.
 * @module model/Answer
 * @version 0.1.0
 */
export class Answer {
  /**
   * Constructs a new <code>Answer</code>.
   * @alias module:model/Answer
   * @class
   * @param text {String} 
   * @param points {Number} 
   * @param revealed {Boolean} 
   */
  constructor(text, points, revealed) {
    this.text = text;
    this.points = points;
    this.revealed = revealed;
  }

  /**
   * Constructs a <code>Answer</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Answer} obj Optional instance to populate.
   * @return {module:model/Answer} The populated <code>Answer</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Answer();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('text'))
        obj.text = ApiClient.convertToType(data['text'], 'String');
      if (data.hasOwnProperty('points'))
        obj.points = ApiClient.convertToType(data['points'], 'Number');
      if (data.hasOwnProperty('revealed'))
        obj.revealed = ApiClient.convertToType(data['revealed'], 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
Answer.prototype.id = undefined;

/**
 * @member {String} text
 */
Answer.prototype.text = undefined;

/**
 * @member {Number} points
 */
Answer.prototype.points = undefined;

/**
 * @member {Boolean} revealed
 */
Answer.prototype.revealed = undefined;


