/*
 * Brood-Clash API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.13
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient';
import {ModelsAnswer} from './ModelsAnswer';

/**
 * The ModelsQuestion model module.
 * @module model/ModelsQuestion
 * @version 1.0
 */
export class ModelsQuestion {
  /**
   * Constructs a new <code>ModelsQuestion</code>.
   * @alias module:model/ModelsQuestion
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ModelsQuestion</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ModelsQuestion} obj Optional instance to populate.
   * @return {module:model/ModelsQuestion} The populated <code>ModelsQuestion</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ModelsQuestion();
      if (data.hasOwnProperty('answers'))
        obj.answers = ApiClient.convertToType(data['answers'], [ModelsAnswer]);
      if (data.hasOwnProperty('hasBeenShown'))
        obj.hasBeenShown = ApiClient.convertToType(data['hasBeenShown'], 'Boolean');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('text'))
        obj.text = ApiClient.convertToType(data['text'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/ModelsAnswer>} answers
 */
ModelsQuestion.prototype.answers = undefined;

/**
 * @member {Boolean} hasBeenShown
 */
ModelsQuestion.prototype.hasBeenShown = undefined;

/**
 * @member {String} id
 */
ModelsQuestion.prototype.id = undefined;

/**
 * @member {String} text
 */
ModelsQuestion.prototype.text = undefined;


