/*
 * Brood Clash
 * Backend API for Brood Clash
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient';
import {Answer} from './Answer';

/**
 * The Question model module.
 * @module model/Question
 * @version 0.1.0
 */
export class Question {
  /**
   * Constructs a new <code>Question</code>.
   * @alias module:model/Question
   * @class
   * @param text {String} 
   */
  constructor(text) {
    this.text = text;
  }

  /**
   * Constructs a <code>Question</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Question} obj Optional instance to populate.
   * @return {module:model/Question} The populated <code>Question</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Question();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('text'))
        obj.text = ApiClient.convertToType(data['text'], 'String');
      if (data.hasOwnProperty('answers'))
        obj.answers = ApiClient.convertToType(data['answers'], [Answer]);
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
Question.prototype.id = undefined;

/**
 * @member {String} text
 */
Question.prototype.text = undefined;

/**
 * @member {Array.<module:model/Answer>} answers
 */
Question.prototype.answers = undefined;


